# Generated by Django 4.2.7 on 2026-01-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskdependency',
            name='unique_task_dependency',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='task_depend_task_id_52f414_idx',
            old_name='task_dependencies_task_id_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='task_depend_depends_af5f16_idx',
            old_name='task_dependencies_depends_on_id_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('task', 'depends_on')},
        ),
    ]
