# Generated by Django 4.2.7 on 2026-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskdependency_unique_task_dependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=8, help_text='Estimated hours to complete this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low (1)'), (2, 'Medium-Low (2)'), (3, 'Medium (3)'), (4, 'Medium-High (4)'), (5, 'High (5)')], default=3, help_text='Task priority from 1 (Low) to 5 (High)'),
        ),
    ]
